repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [ '--maxkb=1024' ]
      - id: no-commit-to-branch
        args: [ --branch, master ]
      - id: check-yaml
      - id: requirements-txt-fixer
      - id: name-tests-test
        args: [ '--django' ]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [ --config, .flake8 ]
        exclude: tests
        stages: [ commit ]

#  - repo: https://github.com/ambv/black
#    rev: 22.3.0
#    hooks:
#      - id: black
#        stages: [ commit ]