name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.10
  - fastapi=0.111.0
  - loguru=0.5.3
  - numpy=1.26.4
  - pandas=2.2.2
  - pydantic=2.7.2
  - python-dotenv=1.0.1
  - requests=2.32.2
  - scikit-learn=1.5.0
  - tqdm=4.65.0
  - pip
  - pytorch
  - pip:
      - sentence-transformers==3.0.0
      - wandb==0.17.0
      - transformers==4.41.1