use_description: true
base_transformer_models: 
 - "microsoft/codebert-base"
model_key: "fcn-transformer"
unfrozen_layers: -1
num_classifiers: 1
val_size: 0.1
test_size: 0.1
dropout: 0.2
learning_rate: 0.000009
epochs: 20
batch_size: 10
max_tokens: 256
early_stopping_patience: null
topk_indices: 
  - 3
  - 5
  - 10
  - 20
run_name: "ts_fcn_codebert_40_classes_last_dev"
weights_save_location: "/work/disa_lab/projects/triagerx/models/typescript"
test_report_location: "/home/mdafifal.mamun/notebooks/triagerX/training/reports/"
wandb_project: "microsoft-ts"
architecture: "-"
dataset: "Microsoft Typescript"