use_description: true
base_transformer_models: 
 - "microsoft/deberta-base"
 - "roberta-base"
unfrozen_layers: 3
num_classifiers: 3
val_size: 0.1
test_size: 0.1
dropout: 0.2
learning_rate: 0.00001
epochs: 20
batch_size: 10
max_tokens: 256
early_stopping_patience: null
topk_indices: 
  - 3
  - 5
  - 10
  - 20
model_key: "triagerx"
run_name: "ts_triagerx_ensemble_u3_40_classes_last_dev"
weights_save_location: "/work/disa_lab/projects/triagerx/models/typescript"
test_report_location: "/home/mdafifal.mamun/notebooks/triagerX/training/reports/"
wandb_project: "microsoft-ts"
architecture: "Triagerx Ensemble"
dataset: "Microsoft Typescript Issues"