project:
  title: "TriagerX for Openj9"
  api_version: "1.0"

similarity_model:
  model_key: "all-mpnet-base-v2"
  embeddings_path: "app/saved_states/train_embeddings.npy"

developer_model:
  config:
    model_key: "triagerx"
    base_models: ["microsoft/deberta-base", "roberta-base"]
    output_size: 50
    unfrozen_layers: 3
    num_classifiers: 3
    dropout: 0.2
    max_tokens: 256
    num_filters: 256
  weights_path: "app/saved_states/triagerx_ensemble_u3_50_classes_last_dev_seed42.pt"

contribution_score_params:
  maximum_similar_issues: 20
  similarity_prediction_weight: 0.65
  similarity_threshold: 0.5
  time_decay_factor: 0.01
  direct_assignment_score: 0.5
  contribution_score: 1.5
  discussion_score: 0.2

data:
  issues_path: "app/app_data/issue_data"
  train_data: "app/app_data/openj9_train.csv"