use_description: true
base_transformer_models: 
 - "microsoft/deberta-base"
model_key: "cnn-transformer"
unfrozen_layers: -1
num_classifiers: 1
val_size: 0.1
test_size: 0.1
dropout: 0.2
learning_rate: 0.00001
epochs: 40
batch_size: 10
max_tokens: 256
early_stopping_patience: null
topk_indices: 
  - 3
  - 5
  - 10
  - 20
run_name: "cnn_deberta-base-full_u3_50_classes_last_dev"
weights_save_location: "/work/disa_lab/projects/triagerx/models/openj9"
test_report_location: "/home/mdafifal.mamun/notebooks/triagerX/training/reports/"
wandb_project: "openj9-developers"
architecture: "-"
dataset: "Openj9 Issues"