use_description: true
base_transformer_models: 
 - "microsoft/deberta-base"
model_key: "cnn-transformer"
unfrozen_layers: 3
num_classifiers: 3
val_size: 0.2
test_size: 0.2
dropout: 0.2
learning_rate: 0.00001
epochs: 50
batch_size: 10
max_tokens: 256
early_stopping_patience: 10
topk_indices: 
  - 3
  - 5
  - 10
run_name: "cnn_deberta-base_u3_42_classes"
weights_save_location: "/work/disa_lab/projects/triagerx/models/"
test_report_location: "/home/mdafifal.mamun/notebooks/triagerX/training/reports/"
wandb_project: "openj9-developers"
architecture: "CNN Deberta"
dataset: "Openj9 Issues"