similarity_model:
  model_key: "all-mpnet-base-v2"

component_model:
  use_special_tokens: false
  use_description: true
  use_summary: false
  base_transformer_model: "microsoft/deberta-base"
  num_classes: 6
  unfrozen_layers: 5
  dropout: 0.2
  topk_indices: 3
  weights_save_location: "model_weights/comp_raw_data_LBTPDeberta_u5_6_classes_seed66.pt"

developer_model:
  use_special_tokens: false
  use_description: true
  use_summary: false
  base_transformer_model: "microsoft/deberta-large"
  num_classes: 15
  unfrozen_layers: 4
  dropout: 0.2
  topk_indices: 3
  weights_save_location: "model_weights/comp_raw_data_LBTPDeberta_u5_6_classes_seed66.pt"

data:
  issues_dir: "data/issue_data"
  train_data: "data/train_data.csv"

tokenizer:
  model_name: "microsoft/deberta-base"
  padding: "max_length"
  max_length: 512
  truncation: True
  return_tensors: "pt"

component_developer_map:
  comp:vm:
    - pshipton
    - keithc-ca
    - gacholio
    - tajila
    - babsingh
    - JasonFengJ9
    - fengxue-IS
    - hangshao0
    - theresa.t.mammarella
    - ChengJin01
    - singh264
    - thallium
    - ThanHenderson
  comp:jvmti:
    - gacholio
    - tajila
    - babsingh
    - fengxue-IS
  comp:jclextensions:
    - JasonFengJ9
    - pshipton
    - keithc-ca
  comp:test:
    - LongyuZhang
    - annaibm
    - sophiaxu0424
    - KapilPowar
    - llxia
  comp:build:
    - adambrousseau
    - mahdipub
  comp:gc:
    - dmitripivkine
    - amicic
    - kangyining
    - LinHu2016

developer_id_map:
  ChengJin01: 0
  JasonFengJ9: 1
  LinHu2016: 2
  LongyuZhang: 3
  amicic: 4
  babsingh: 5
  dmitripivkine: 6
  fengxue-IS: 7
  gacholio: 8
  hangshao0: 9
  keithc-ca: 10
  llxia: 11
  pshipton: 12
  tajila: 13
  thallium: 14

component_id_map:
  comp:build: 0
  comp:gc: 1
  comp:jclextensions: 2
  comp:jvmti: 3
  comp:test: 4
  comp:vm: 5