use_special_tokens: false
use_description: false
use_summary: true
dataset_path: "/home/mdafifal.mamun/notebooks/triagerX/notebook/data/openj9/component_training/df_all_summarized.csv"
target_components:
  - "comp:vm"
  - "comp:jvmti"
  - "comp:jclextensions"
  - "comp:test"
  - "comp:build"
  - "comp:gc"
base_transformer_model: "microsoft/deberta-base"
unfrozen_layers: 5
val_size: 0.2
test_size: 0.2
dropout: 0.2
learning_rate: 0.00001
epochs: 50
batch_size: 10
early_stopping_patience: 10
topk_indices: 3
run_name: "comp_summary_LBTPDeberta_u5_6_classes"
weights_save_location: "/work/disa_lab/projects/triagerx/models/"
test_report_location: "/home/mdafifal.mamun/notebooks/triagerX/training/reports/"
wandb_project: "openj9-component"
architecture: "LBTP-Deberta"
dataset: "Openj9 Issues"