use_special_tokens: true
use_summary: false
dataset_path: "/home/mdafifal.mamun/notebooks/triagerX/notebook/data/openj9/openj9_processed.csv"
target_components:
  - "comp:vm"
  - "comp:jvmti"
  - "comp:jclextensions"
  - "comp:test"
  - "comp:build"
  - "comp:gc"
base_transformer_model: "microsoft/deberta-base"
unfrozen_layers: 5
seed: 41
val_size: 0.2
test_size: 0.2
dropout: 0.2
learning_rate: 0.00001
epochs: 50
batch_size: 10
early_stopping_patience: 10
topk_indices: 3
run_name: "comp_sp_tokens_LBTPDeberta_u5_6_classes"
weights_save_location: "/work/disa_lab/projects/triagerx/models/comp_sp_tokens_LBTPDeberta_u5_6_classes.pt"
test_report_location: "/home/mdafifal.mamun/notebooks/triagerX/notebook/data/openj9/reports/classification_report_comp_sp_tokens_LBTPDeberta_u5_6_classes.json"
wandb_project: "openj9-component"
architecture: "LBTP-Deberta"
dataset: "Openj9 Issues"