use_description: true
base_transformer_models: 
 - "microsoft/deberta-large"
model_key: "cnn-transformer"
unfrozen_layers: 3
num_classifiers: 3
total_folds: 10
fold_number: 9
val_size: 0.2
test_size: 0.2
dropout: 0.2
learning_rate: 0.00001
epochs: 50
batch_size: 10
max_tokens: 256
early_stopping_patience: 7
topk_indices:
  - 3
  - 5
  - 10
run_name: "cnn_deberta-large_dt_mc"
weights_save_location: "/work/disa_lab/projects/triagerx/models/deeptriage"
test_report_location: "/home/mdafifal.mamun/notebooks/triagerX/training/reports/"
wandb_project: "lbtp_reproduction"
architecture: "Deberta Large - CNN"
dataset: "Deeptriage Issues"