use_special_tokens: true
use_description: true
use_summary: false
dataset_path: "/home/mdafifal.mamun/notebooks/triagerX/notebook/data/deeptriage/classifier_data_20.csv"
base_transformer_model: "microsoft/deberta-large"
unfrozen_layers: 4
total_folds: 10
fold_number: 9
dropout: 0.2
learning_rate: 0.00001
epochs: 10
batch_size: 10
early_stopping_patience: 10
topk_indices: 10
run_name: "triagerx_dt_gc"
weights_save_location: "/work/disa_lab/projects/triagerx/models/"
test_report_location: "/home/mdafifal.mamun/notebooks/triagerX/training/reports/"
wandb_project: "lbtp_reproduction"
architecture: "LBTP-Deberta"
dataset: "Deeptriage Issues"