use_description: true
base_transformer_models: 
 - "microsoft/deberta-base"
 - "roberta-base"
model_key: "triagerx"
unfrozen_layers: 3
num_classifiers: 3
total_folds: 10
fold_number: 9
val_size: 0.2
test_size: 0.2
dropout: 0.2
learning_rate: 0.00001
epochs: 20
batch_size: 10
max_tokens: 256
early_stopping_patience: 5
topk_indices:
  - 3
  - 5
  - 10
  - 20
run_name: "triagerx_gc_ensemble_deberta_roberta_base"
weights_save_location: "/work/disa_lab/projects/triagerx/models/deeptriage"
test_report_location: "/home/mdafifal.mamun/notebooks/triagerX/training/reports/"
wandb_project: "google_chromium"
architecture: "TriagerxDevModel"
dataset: "Deeptriage Issues"