use_description: true
base_transformer_models: 
 - "microsoft/codebert-base"
model_key: "cnn-transformer"
unfrozen_layers: -1
num_classifiers: 1
total_folds: 10
fold_number: 9
val_size: 0.2
test_size: 0.2
dropout: 0.2
learning_rate: 0.00001
epochs: 15
batch_size: 20
max_tokens: 256
early_stopping_patience: null
topk_indices:
  - 3
  - 5
  - 10
  - 20
run_name: "mc_cnn_codebert_dt_th20"
weights_save_location: "/work/disa_lab/projects/triagerx/models/deeptriage"
test_report_location: "/home/mdafifal.mamun/notebooks/triagerX/training/reports/"
wandb_project: "mozilla_core"
architecture: "-"
dataset: "Deeptriage Issues"